// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"tool-agent/model"
)

func newKbDocument(db *gorm.DB, opts ...gen.DOOption) kbDocument {
	_kbDocument := kbDocument{}

	_kbDocument.kbDocumentDo.UseDB(db, opts...)
	_kbDocument.kbDocumentDo.UseModel(&model.KbDocument{})

	tableName := _kbDocument.kbDocumentDo.TableName()
	_kbDocument.ALL = field.NewAsterisk(tableName)
	_kbDocument.Id = field.NewUint64(tableName, "id")
	_kbDocument.Title = field.NewString(tableName, "title")
	_kbDocument.Content = field.NewString(tableName, "content")
	_kbDocument.Embedding = field.NewString(tableName, "embedding")
	_kbDocument.CreatedAt = field.NewTime(tableName, "created_at")
	_kbDocument.UpdatedAt = field.NewTime(tableName, "updated_at")
	_kbDocument.DeletedAt = field.NewField(tableName, "deleted_at")

	_kbDocument.fillFieldMap()

	return _kbDocument
}

type kbDocument struct {
	kbDocumentDo

	ALL       field.Asterisk
	Id        field.Uint64 // 主键
	Title     field.String // 文档标题
	Content   field.String // 文档内容
	Embedding field.String // 向量JSON
	CreatedAt field.Time   // 添加时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (k kbDocument) Table(newTableName string) *kbDocument {
	k.kbDocumentDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kbDocument) As(alias string) *kbDocument {
	k.kbDocumentDo.DO = *(k.kbDocumentDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kbDocument) updateTableName(table string) *kbDocument {
	k.ALL = field.NewAsterisk(table)
	k.Id = field.NewUint64(table, "id")
	k.Title = field.NewString(table, "title")
	k.Content = field.NewString(table, "content")
	k.Embedding = field.NewString(table, "embedding")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.DeletedAt = field.NewField(table, "deleted_at")

	k.fillFieldMap()

	return k
}

func (k *kbDocument) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kbDocument) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 7)
	k.fieldMap["id"] = k.Id
	k.fieldMap["title"] = k.Title
	k.fieldMap["content"] = k.Content
	k.fieldMap["embedding"] = k.Embedding
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["deleted_at"] = k.DeletedAt
}

func (k kbDocument) clone(db *gorm.DB) kbDocument {
	k.kbDocumentDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kbDocument) replaceDB(db *gorm.DB) kbDocument {
	k.kbDocumentDo.ReplaceDB(db)
	return k
}

type kbDocumentDo struct{ gen.DO }

type IKbDocumentDo interface {
	gen.SubQuery
	Debug() IKbDocumentDo
	WithContext(ctx context.Context) IKbDocumentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKbDocumentDo
	WriteDB() IKbDocumentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKbDocumentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKbDocumentDo
	Not(conds ...gen.Condition) IKbDocumentDo
	Or(conds ...gen.Condition) IKbDocumentDo
	Select(conds ...field.Expr) IKbDocumentDo
	Where(conds ...gen.Condition) IKbDocumentDo
	Order(conds ...field.Expr) IKbDocumentDo
	Distinct(cols ...field.Expr) IKbDocumentDo
	Omit(cols ...field.Expr) IKbDocumentDo
	Join(table schema.Tabler, on ...field.Expr) IKbDocumentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKbDocumentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKbDocumentDo
	Group(cols ...field.Expr) IKbDocumentDo
	Having(conds ...gen.Condition) IKbDocumentDo
	Limit(limit int) IKbDocumentDo
	Offset(offset int) IKbDocumentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKbDocumentDo
	Unscoped() IKbDocumentDo
	Create(values ...*model.KbDocument) error
	CreateInBatches(values []*model.KbDocument, batchSize int) error
	Save(values ...*model.KbDocument) error
	First() (*model.KbDocument, error)
	Take() (*model.KbDocument, error)
	Last() (*model.KbDocument, error)
	Find() ([]*model.KbDocument, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KbDocument, err error)
	FindInBatches(result *[]*model.KbDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KbDocument) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKbDocumentDo
	Assign(attrs ...field.AssignExpr) IKbDocumentDo
	Joins(fields ...field.RelationField) IKbDocumentDo
	Preload(fields ...field.RelationField) IKbDocumentDo
	FirstOrInit() (*model.KbDocument, error)
	FirstOrCreate() (*model.KbDocument, error)
	FindByPage(offset int, limit int) (result []*model.KbDocument, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKbDocumentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kbDocumentDo) Debug() IKbDocumentDo {
	return k.withDO(k.DO.Debug())
}

func (k kbDocumentDo) WithContext(ctx context.Context) IKbDocumentDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kbDocumentDo) ReadDB() IKbDocumentDo {
	return k.Clauses(dbresolver.Read)
}

func (k kbDocumentDo) WriteDB() IKbDocumentDo {
	return k.Clauses(dbresolver.Write)
}

func (k kbDocumentDo) Session(config *gorm.Session) IKbDocumentDo {
	return k.withDO(k.DO.Session(config))
}

func (k kbDocumentDo) Clauses(conds ...clause.Expression) IKbDocumentDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kbDocumentDo) Returning(value interface{}, columns ...string) IKbDocumentDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kbDocumentDo) Not(conds ...gen.Condition) IKbDocumentDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kbDocumentDo) Or(conds ...gen.Condition) IKbDocumentDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kbDocumentDo) Select(conds ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kbDocumentDo) Where(conds ...gen.Condition) IKbDocumentDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kbDocumentDo) Order(conds ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kbDocumentDo) Distinct(cols ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kbDocumentDo) Omit(cols ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kbDocumentDo) Join(table schema.Tabler, on ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kbDocumentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kbDocumentDo) RightJoin(table schema.Tabler, on ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kbDocumentDo) Group(cols ...field.Expr) IKbDocumentDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kbDocumentDo) Having(conds ...gen.Condition) IKbDocumentDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kbDocumentDo) Limit(limit int) IKbDocumentDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kbDocumentDo) Offset(offset int) IKbDocumentDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kbDocumentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKbDocumentDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kbDocumentDo) Unscoped() IKbDocumentDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kbDocumentDo) Create(values ...*model.KbDocument) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kbDocumentDo) CreateInBatches(values []*model.KbDocument, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kbDocumentDo) Save(values ...*model.KbDocument) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kbDocumentDo) First() (*model.KbDocument, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KbDocument), nil
	}
}

func (k kbDocumentDo) Take() (*model.KbDocument, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KbDocument), nil
	}
}

func (k kbDocumentDo) Last() (*model.KbDocument, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KbDocument), nil
	}
}

func (k kbDocumentDo) Find() ([]*model.KbDocument, error) {
	result, err := k.DO.Find()
	return result.([]*model.KbDocument), err
}

func (k kbDocumentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KbDocument, err error) {
	buf := make([]*model.KbDocument, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kbDocumentDo) FindInBatches(result *[]*model.KbDocument, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kbDocumentDo) Attrs(attrs ...field.AssignExpr) IKbDocumentDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kbDocumentDo) Assign(attrs ...field.AssignExpr) IKbDocumentDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kbDocumentDo) Joins(fields ...field.RelationField) IKbDocumentDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kbDocumentDo) Preload(fields ...field.RelationField) IKbDocumentDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kbDocumentDo) FirstOrInit() (*model.KbDocument, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KbDocument), nil
	}
}

func (k kbDocumentDo) FirstOrCreate() (*model.KbDocument, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KbDocument), nil
	}
}

func (k kbDocumentDo) FindByPage(offset int, limit int) (result []*model.KbDocument, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kbDocumentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kbDocumentDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kbDocumentDo) Delete(models ...*model.KbDocument) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kbDocumentDo) withDO(do gen.Dao) *kbDocumentDo {
	k.DO = *do.(*gen.DO)
	return k
}
